import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';

import styled from 'styled-components';

import Heading from '../components/heading/Heading';

const Demo = styled.div`
	background: red;
	width: 200px;
	height: 150px;
`;

export default function Home() {
	return (
		<div className={styles.container}>
			<Head>
				<title>Create Next App</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />

				<link rel='preconnect' href='https://fonts.googleapis.com' />
				<link rel='preconnect' href='https://fonts.gstatic.com' crossorigin />
				<link
					href='https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,400;0,700;0,900;1,400;1,700;1,900&display=swap'
					rel='stylesheet'
				/>
			</Head>

			<main className={styles.main}>
				<Heading>I love it</Heading>
			</main>
		</div>
	);
}
