const listOfCourses = [
    {
        id: 1,
        date: '2023',
        title: 'Node.js and Express.js Full Course',
        lecturer: 'John Smilga, FreeCodeCamp',
        description: '',
    },
    {
        id: 2,
        date: '2023',
        title: 'Getting started with Hydrogen',
        lecturer: 'Sanity.io',
        description: '',
    },
    {
        id: 3,
        date: '2023',
        title: 'First frontend foray',
        lecturer: 'Sanity.io',
        description: '',
    },
    {
        id: 4,
        date: '2023',
        title: 'Between GROQ and a hard place',
        lecturer: 'Sanity.io',
        description: '',
    },
    {
        id: 5,
        date: '2023',
        title: 'Introduction to GROQ Query Language',
        lecturer: 'Egghead, John Lindquist',
        description: '',
    },
    {
        id: 6,
        date: '2023',
        title: 'Day One with Sanity Studio',
        lecturer: 'Sanity.io',
        description: '',
    },
    {
        id: 7,
        date: '2022',
        title: 'Build Static Pages Dynamically using Next.js and the Notion Api',
        lecturer: 'Egghead, Jon Meyers',
        description: '',
    },
    {
        id: 8,
        date: '2022',
        title: 'Design Systems with React and Typescript in Storybook',
        lecturer: 'Egghead, Shawn Wang',
        description: '',
    },
    {
        id: 9,
        date: '2022',
        title: 'Next.js By Example',
        lecturer: 'Udemy, Mirko Nasato',
        description: '',
    },
    {
        id: 10,
        date: '2022',
        title: 'Fundamentals of Digital Marketing',
        lecturer: 'Google',
        description: '',
    },
    {
        id: 11,
        date: '2020',
        title: 'Web Development',
        lecturer: 'Code Academy',
        description: '',
    },
    {
        id: 12,
        date: '2019',
        title: 'Javascript Projects',
        lecturer: 'Udemy.com, Rob Merrill',
        description: '',
    },
    {
        id: 13,
        date: '2019',
        title: 'Web Design with HTML & CSS',
        lecturer: 'Code College',
        description: '',
    },
]

export default listOfCourses
